### ISSUE TITLE
How to generate the specified 3D motion

### ISSUE THREAD

**Issue by XingliangJin** [roykapon/MAS#7]
In your paper, the visual comparison experiment seems to require the generation of specified 3D motion. However, the method uses 2d diffusion with unconditional training. So, how do you generate the specified 3D motion?

**Comment by roykapon** [comment]
Hello @XingliangJin  :)
I'm not sure I understood your question properly. The visual comparison experiment is unconditioned, meaning we just took some random generations (not necessarily of the same type) and compared them.

**Comment by XingliangJin** [comment]
Thank you！I mistakenly thought that the comparison methods showed the same type of motions.
